Add AC_USE_SYSTEM_EXTENSIONS to expose non-standard extensions
Required on Solaris to expose fd_mask in <sys/select.h> now that
xtrans 1.3 defines _XOPEN_SOURCE to 600 on Solaris, since fd_mask
is not defined in that version of the XPG standards.

Fixes build failure:
os/connection.c: In function ‘CreateServerSockets’:
os/connection.c:335:10: error: ‘fd_mask’ undeclared (first use in this function)
os/connection.c:335:10: note: each undeclared identifier is reported only once for each function it appears in
os/connection.c: In function ‘ListenWellKnownSockets’:
os/connection.c:416:5: error: ‘fd_mask’ undeclared (first use in this function)
os/connection.c: In function ‘EstablishNewConnections’:
os/connection.c:562:5: error: ‘fd_mask’ undeclared (first use in this function)
os/connection.c: In function ‘CloseDownFileDescriptor’:
os/connection.c:684:10: error: ‘fd_mask’ undeclared (first use in this function)
os/connection.c: In function ‘CheckConnections’:
os/connection.c:701:5: error: unknown type name ‘fd_mask’
os/connection.c:711:17: error: ‘fd_mask’ undeclared (first use in this function)
os/connection.c: In function ‘OnlyListenToOneClient’:
os/connection.c:770:2: error: ‘fd_mask’ undeclared (first use in this function)
os/connection.c: In function ‘ListenToAllClients’:
os/connection.c:801:2: error: ‘fd_mask’ undeclared (first use in this function)

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Reviewed-by: Daniel Stone <daniel@fooishbar.org>