Cast pointer to long instead of int
Matches the cast passed in ((pointer)(long) server->index on line 1276)
Fixes gcc error:
di/wire.c:1119:27: error: cast from pointer to integer of different size

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>